
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

create table polls
(
    id          integer generated by default as identity
        constraint polls_pkey
            primary key,
    token       uuid default uuid_generate_v4() not null,
    project_id  varchar                         not null,
    type        varchar                         not null,
    state       varchar,
    description varchar,
    name        varchar,
    version     serial,
    updatedAt date,
    createdAt date
);

alter table polls
    owner to postgres;
